<a href="https://colab.research.google.com/github/juhumkwon/DataMining/blob/main/1_2_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Iris 데이터 로드

from sklearn.datasets import load_iris
import pandas as pd

# 데이터 로드
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [ ]:
#preprocessing
"""
주요 기능
스케일링: StandardScaler, MinMaxScaler
인코딩: LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
import numpy as np
"""
from sklearn.preprocessing import StandardScaler
import numpy as np

# 데이터 생성
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 표준화
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)


[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [ ]:
#model_selection
"""
train_test_split: 데이터를 학습/테스트 세트로 분리
cross_val_score: 교차 검증 점수 계산
"""

from sklearn.model_selection import train_test_split

# 데이터 생성
X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]

# 학습/테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print("Train:", X_train, y_train)
print("Test:", X_test, y_test)


Train: [[7, 8], [1, 2], [5, 6]] [1, 0, 0]
Test: [[3, 4]] [1]


In [ ]:
#metrics
"""
분류: accuracy_score, confusion_matrix
회귀: mean_squared_error, r2_score
"""

from sklearn.metrics import accuracy_score

# 실제 값과 예측 값
y_true = [0, 1, 1, 0]
y_pred = [0, 1, 0, 0]

# 정확도 계산
accuracy = accuracy_score(y_true, y_pred)
print(f"Accuracy: {accuracy}")


Accuracy: 0.75


In [ ]:
#선형 회귀
from sklearn.linear_model import LinearRegression
import numpy as np

"""
LinearRegression: 선형 회귀
LogisticRegression: 로지스틱 회귀
"""

# 데이터 생성
X = np.array([[1], [2], [3], [4]])
y = np.array([2.2, 2.8, 3.6, 4.5])

# 모델 학습
model = LinearRegression()
model.fit(X, y)

# 예측
y_pred = model.predict([[5]])
print(f"Prediction for 5: {y_pred}")


Prediction for 5: [5.2]


In [ ]:
# 앙상불 ensemble
"""
주요 모델
RandomForestClassifier: 랜덤 포레스트
GradientBoostingClassifier: 그래디언트 부스팅
"""
#랜덤 포레스트 에제

from sklearn.ensemble import RandomForestClassifier

# 데이터 생성
X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]

# 모델 학습
clf = RandomForestClassifier(n_estimators=10, random_state=42)
clf.fit(X, y)

# 예측
print(clf.predict([[3, 4]]))


[1]


In [ ]:
#PCA: 주성분 분석

from sklearn.decomposition import PCA
import numpy as np

# 데이터 생성
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# PCA 적용
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)
print(X_reduced)


[[-5.19615242e+00 -2.56395025e-16]
 [ 0.00000000e+00 -0.00000000e+00]
 [ 5.19615242e+00 -2.56395025e-16]]


In [ ]:
#cluster

from sklearn.cluster import KMeans
import numpy as np

# 데이터 생성
X = np.array([[1, 2], [1, 4], [1, 0], [4, 2], [4, 4], [4, 0]])

# KMeans 적용
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X)

# 클러스터 할당
print(kmeans.labels_)


[0 1 0 1 1 0]
